swagger: "2.0"
info:
  version: "0.0.1"
  title: Conteka Microservice Server
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json


# Here begins the path descriptions
paths:
  /get-data:
    # binds a127 app logic to a route
    x-swagger-router-controller: action-controller
    post:
      description: A data agnostic fetch API
      # used as the method name of the controller
      operationId: getData
      parameters:
        - in: query
          name: collection
          type: string
          description: The name of collection to fetch
          required: true
        - in: body
          name: filteroption
          schema:
            type: object
          description: The filter to fetch specific records
          required: false
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetDataResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /save-data:
    # binds a127 app logic to a route
    x-swagger-router-controller: action-controller
    post:
      description: A data agnostic save API
      # used as the method name of the controller
      operationId: postData
      parameters:
        - in: query
          name: collection
          type: string
          description: The name of collection to save to
          required: true
        - in: body
          name: record
          schema:
            type: object
          description: The record to save to the collection
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetDataResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /get-collections:
    # binds a127 app logic to a route
    x-swagger-router-controller: action-controller
    get:
      description: A data agnostic save API
      # used as the method name of the controller
      operationId: getAllCollectionNames
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetDataResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw

# complex objects have schema definitions
definitions:
  GetDataResponse:
    properties:
      data:
        type: object
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
